// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dash.proto

package gnmi_sonic

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DashRoute struct {
	Eni                  string   `protobuf:"bytes,1,opt,name=eni,proto3" json:"eni,omitempty"`
	Prefix               string   `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	IpVersion            string   `protobuf:"bytes,3,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version,omitempty"`
	RoutingType          string   `protobuf:"bytes,4,opt,name=routing_type,json=routingType,proto3" json:"routing_type,omitempty"`
	Vnet                 string   `protobuf:"bytes,5,opt,name=vnet,proto3" json:"vnet,omitempty"`
	CustomerAddr         string   `protobuf:"bytes,6,opt,name=customer_addr,json=customerAddr,proto3" json:"customer_addr,omitempty"`
	Appliance            string   `protobuf:"bytes,7,opt,name=appliance,proto3" json:"appliance,omitempty"`
	UnderlayIp           string   `protobuf:"bytes,8,opt,name=underlay_ip,json=underlayIp,proto3" json:"underlay_ip,omitempty"`
	OverlaySip           string   `protobuf:"bytes,9,opt,name=overlay_sip,json=overlaySip,proto3" json:"overlay_sip,omitempty"`
	OverlayDip           string   `protobuf:"bytes,10,opt,name=overlay_dip,json=overlayDip,proto3" json:"overlay_dip,omitempty"`
	MeteringBucket       string   `protobuf:"bytes,11,opt,name=metering_bucket,json=meteringBucket,proto3" json:"metering_bucket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DashRoute) Reset()         { *m = DashRoute{} }
func (m *DashRoute) String() string { return proto.CompactTextString(m) }
func (*DashRoute) ProtoMessage()    {}
func (*DashRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73fe6107bbb205f, []int{0}
}

func (m *DashRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashRoute.Unmarshal(m, b)
}
func (m *DashRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashRoute.Marshal(b, m, deterministic)
}
func (m *DashRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashRoute.Merge(m, src)
}
func (m *DashRoute) XXX_Size() int {
	return xxx_messageInfo_DashRoute.Size(m)
}
func (m *DashRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_DashRoute.DiscardUnknown(m)
}

var xxx_messageInfo_DashRoute proto.InternalMessageInfo

func (m *DashRoute) GetEni() string {
	if m != nil {
		return m.Eni
	}
	return ""
}

func (m *DashRoute) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *DashRoute) GetIpVersion() string {
	if m != nil {
		return m.IpVersion
	}
	return ""
}

func (m *DashRoute) GetRoutingType() string {
	if m != nil {
		return m.RoutingType
	}
	return ""
}

func (m *DashRoute) GetVnet() string {
	if m != nil {
		return m.Vnet
	}
	return ""
}

func (m *DashRoute) GetCustomerAddr() string {
	if m != nil {
		return m.CustomerAddr
	}
	return ""
}

func (m *DashRoute) GetAppliance() string {
	if m != nil {
		return m.Appliance
	}
	return ""
}

func (m *DashRoute) GetUnderlayIp() string {
	if m != nil {
		return m.UnderlayIp
	}
	return ""
}

func (m *DashRoute) GetOverlaySip() string {
	if m != nil {
		return m.OverlaySip
	}
	return ""
}

func (m *DashRoute) GetOverlayDip() string {
	if m != nil {
		return m.OverlayDip
	}
	return ""
}

func (m *DashRoute) GetMeteringBucket() string {
	if m != nil {
		return m.MeteringBucket
	}
	return ""
}

type DashRouteTable struct {
	Routes               []*DashRoute `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *DashRouteTable) Reset()         { *m = DashRouteTable{} }
func (m *DashRouteTable) String() string { return proto.CompactTextString(m) }
func (*DashRouteTable) ProtoMessage()    {}
func (*DashRouteTable) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73fe6107bbb205f, []int{1}
}

func (m *DashRouteTable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashRouteTable.Unmarshal(m, b)
}
func (m *DashRouteTable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashRouteTable.Marshal(b, m, deterministic)
}
func (m *DashRouteTable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashRouteTable.Merge(m, src)
}
func (m *DashRouteTable) XXX_Size() int {
	return xxx_messageInfo_DashRouteTable.Size(m)
}
func (m *DashRouteTable) XXX_DiscardUnknown() {
	xxx_messageInfo_DashRouteTable.DiscardUnknown(m)
}

var xxx_messageInfo_DashRouteTable proto.InternalMessageInfo

func (m *DashRouteTable) GetRoutes() []*DashRoute {
	if m != nil {
		return m.Routes
	}
	return nil
}

func init() {
	proto.RegisterType((*DashRoute)(nil), "gnmi.sonic.DashRoute")
	proto.RegisterType((*DashRouteTable)(nil), "gnmi.sonic.DashRouteTable")
}

func init() { proto.RegisterFile("dash.proto", fileDescriptor_d73fe6107bbb205f) }

var fileDescriptor_d73fe6107bbb205f = []byte{
	// 298 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4d, 0x4e, 0xf3, 0x30,
	0x10, 0x40, 0xd5, 0x9f, 0x2f, 0x1f, 0x99, 0x94, 0x82, 0x2c, 0x81, 0xbc, 0x00, 0x51, 0xca, 0x82,
	0x6e, 0xc8, 0x02, 0x0e, 0x80, 0x40, 0xdd, 0xb0, 0x2d, 0x15, 0xdb, 0xc8, 0x8d, 0x87, 0x76, 0x44,
	0x6b, 0x8f, 0x6c, 0xa7, 0xa2, 0x57, 0xe5, 0x34, 0x28, 0x4e, 0x5a, 0xd4, 0xdd, 0xe4, 0xbd, 0x27,
	0x45, 0x9e, 0x01, 0xd0, 0xca, 0xaf, 0x72, 0x76, 0x36, 0x58, 0x01, 0x4b, 0xb3, 0xa1, 0xdc, 0x5b,
	0x43, 0xe5, 0xf8, 0xa7, 0x0b, 0xe9, 0x54, 0xf9, 0xd5, 0xcc, 0x56, 0x01, 0xc5, 0x39, 0xf4, 0xd0,
	0x90, 0xec, 0x8c, 0x3a, 0x93, 0x74, 0x56, 0x8f, 0xe2, 0x12, 0x12, 0x76, 0xf8, 0x49, 0xdf, 0xb2,
	0x1b, 0x61, 0xfb, 0x25, 0xae, 0x01, 0x88, 0x8b, 0x2d, 0x3a, 0x4f, 0xd6, 0xc8, 0x5e, 0x74, 0x29,
	0xf1, 0x47, 0x03, 0xc4, 0x2d, 0x0c, 0x9c, 0xad, 0x02, 0x99, 0x65, 0x11, 0x76, 0x8c, 0xb2, 0x1f,
	0x83, 0xac, 0x65, 0xf3, 0x1d, 0xa3, 0x10, 0xd0, 0xdf, 0x1a, 0x0c, 0xf2, 0x5f, 0x54, 0x71, 0x16,
	0x77, 0x70, 0x5a, 0x56, 0x3e, 0xd8, 0x0d, 0xba, 0x42, 0x69, 0xed, 0x64, 0x12, 0xe5, 0x60, 0x0f,
	0x5f, 0xb4, 0x76, 0xe2, 0x0a, 0x52, 0xc5, 0xbc, 0x26, 0x65, 0x4a, 0x94, 0xff, 0x9b, 0x3f, 0x1f,
	0x80, 0xb8, 0x81, 0xac, 0x32, 0x1a, 0xdd, 0x5a, 0xed, 0x0a, 0x62, 0x79, 0x12, 0x3d, 0xec, 0xd1,
	0x1b, 0xd7, 0x81, 0xdd, 0x36, 0xde, 0x13, 0xcb, 0xb4, 0x09, 0x5a, 0xf4, 0x4e, 0x47, 0x81, 0x26,
	0x96, 0x70, 0x14, 0x4c, 0x89, 0xc5, 0x3d, 0x9c, 0x6d, 0x30, 0xa0, 0xab, 0x5f, 0xb7, 0xa8, 0xca,
	0x2f, 0x0c, 0x32, 0x8b, 0xd1, 0x70, 0x8f, 0x5f, 0x23, 0x1d, 0x3f, 0xc3, 0xf0, 0xb0, 0xdb, 0xb9,
	0x5a, 0xac, 0x51, 0x3c, 0x40, 0x52, 0xef, 0x00, 0xbd, 0xec, 0x8c, 0x7a, 0x93, 0xec, 0xf1, 0x22,
	0xff, 0xbb, 0x45, 0x7e, 0x68, 0x67, 0x6d, 0xb4, 0x48, 0xe2, 0xc1, 0x9e, 0x7e, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x82, 0xfb, 0x3d, 0x8e, 0xbe, 0x01, 0x00, 0x00,
}
