# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dash.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dash.proto',
  package='gnmi.sonic',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\ndash.proto\x12\ngnmi.sonic\"\xe2\x01\n\tDashRoute\x12\x0b\n\x03\x65ni\x18\x01 \x01(\t\x12\x0e\n\x06prefix\x18\x02 \x01(\t\x12\x12\n\nip_version\x18\x03 \x01(\t\x12\x14\n\x0crouting_type\x18\x04 \x01(\t\x12\x0c\n\x04vnet\x18\x05 \x01(\t\x12\x15\n\rcustomer_addr\x18\x06 \x01(\t\x12\x11\n\tappliance\x18\x07 \x01(\t\x12\x13\n\x0bunderlay_ip\x18\x08 \x01(\t\x12\x13\n\x0boverlay_sip\x18\t \x01(\t\x12\x13\n\x0boverlay_dip\x18\n \x01(\t\x12\x17\n\x0fmetering_bucket\x18\x0b \x01(\t\"7\n\x0e\x44\x61shRouteTable\x12%\n\x06routes\x18\x01 \x03(\x0b\x32\x15.gnmi.sonic.DashRouteb\x06proto3')
)




_DASHROUTE = _descriptor.Descriptor(
  name='DashRoute',
  full_name='gnmi.sonic.DashRoute',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eni', full_name='gnmi.sonic.DashRoute.eni', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prefix', full_name='gnmi.sonic.DashRoute.prefix', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip_version', full_name='gnmi.sonic.DashRoute.ip_version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='routing_type', full_name='gnmi.sonic.DashRoute.routing_type', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vnet', full_name='gnmi.sonic.DashRoute.vnet', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='customer_addr', full_name='gnmi.sonic.DashRoute.customer_addr', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='appliance', full_name='gnmi.sonic.DashRoute.appliance', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='underlay_ip', full_name='gnmi.sonic.DashRoute.underlay_ip', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overlay_sip', full_name='gnmi.sonic.DashRoute.overlay_sip', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='overlay_dip', full_name='gnmi.sonic.DashRoute.overlay_dip', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metering_bucket', full_name='gnmi.sonic.DashRoute.metering_bucket', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=253,
)


_DASHROUTETABLE = _descriptor.Descriptor(
  name='DashRouteTable',
  full_name='gnmi.sonic.DashRouteTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='routes', full_name='gnmi.sonic.DashRouteTable.routes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=255,
  serialized_end=310,
)

_DASHROUTETABLE.fields_by_name['routes'].message_type = _DASHROUTE
DESCRIPTOR.message_types_by_name['DashRoute'] = _DASHROUTE
DESCRIPTOR.message_types_by_name['DashRouteTable'] = _DASHROUTETABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DashRoute = _reflection.GeneratedProtocolMessageType('DashRoute', (_message.Message,), dict(
  DESCRIPTOR = _DASHROUTE,
  __module__ = 'dash_pb2'
  # @@protoc_insertion_point(class_scope:gnmi.sonic.DashRoute)
  ))
_sym_db.RegisterMessage(DashRoute)

DashRouteTable = _reflection.GeneratedProtocolMessageType('DashRouteTable', (_message.Message,), dict(
  DESCRIPTOR = _DASHROUTETABLE,
  __module__ = 'dash_pb2'
  # @@protoc_insertion_point(class_scope:gnmi.sonic.DashRouteTable)
  ))
_sym_db.RegisterMessage(DashRouteTable)


# @@protoc_insertion_point(module_scope)
